spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviefun_dev
    username: moviefun
    password: moviefun

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

debug: true